spring:
  datasource:
    url: jdbc:mysql://localhost:3306/jwt_security_2
    username: root
    password:

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
